# FILE LOCATION: docker-compose.yml (root directory)
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: legal-estate-backend
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "postgresql://legalestate_admin:LegalTechSecure2024@host.docker.internal:5432/legal_estate"
      JWT_SECRET: "demo-jwt-secret-reset-daily"
      JWT_EXPIRES_IN: "24h"
      NODE_ENV: "demo"
      PORT: "3000"
      FRONTEND_URL: "https://legalestate.tech"
      PACKAGE_TYPE: "demo"
      DEMO_MODE: "true"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
      - /mnt/HC_Volume_103506631/docker-data/legalestate-demo/uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - legal-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: legal-estate-frontend
    ports:
      - "8080:3000"
    environment:
      REACT_APP_API_URL: "https://legalestate.tech/api"
      REACT_APP_NAME: "Legal Estate Demo"
      REACT_APP_VERSION: "1.0.0-demo"
      REACT_APP_DEMO_MODE: "true"
      REACT_APP_PACKAGE_TYPE: "demo"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/build
    restart: unless-stopped
    networks:
      - legal-network

networks:
  legal-network:
    driver: bridge