# FILE LOCATION: docker-compose.yml (root directory)
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: legal-estate-backend
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_VWySqE6HnUm9@ep-fancy-tooth-a5z610oe-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
      JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
      JWT_EXPIRES_IN: "24h"
      NODE_ENV: "production"
      PORT: "3000"
      FRONTEND_URL: "http://localhost:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/dist
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - legal-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: legal-estate-frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:3001"
      REACT_APP_NAME: "Legal Estate Management"
      REACT_APP_VERSION: "1.0.0"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/build
    restart: unless-stopped
    networks:
      - legal-network

networks:
  legal-network:
    driver: bridge